---
title: "Codebook"
author: "Paul K. Courtney"
date: "April 26, 2015"
output: html_document
---

**Codebook**


###Subject_ID
*data type* numeric
*meaning* Each subject is identified only with an ID. There were 30 subjects, so the Subject_ID runs from 1 to 30.

###Activities
*data type* character
*meaning* Each person performed six activities (WALKING, WALKING UPSTAIRS, WALKING DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist.

##Features

*data type* character

*meaning* The names of the features are made up of the following parts:

* Time or Freq, with the Time indicating data in the time domain, Freq indicating data in the frequency domain.

* Body or Gravity, with the acceleration or gyroscopic signal separated into body and gravity acceleration or gyroscopic signals

*Acc or Gyro, with Acc meaning linear acceleration and Gyro indicating angular velocity.

*Jerk is used to indicate a sudden change in either Acceleration or Gyroscopic values

*mean or std indicate a value for either a mean or a standard deviation of the data

*XYZ indicate the direction of the linear movement

*Mag indicates the magnitude of the three-dimensional signals  calculated using the Euclidean norm

Time-Body-Acc-mean-X

Time-Body-Acc-mean-Y

Time-Body-Acc-mean-Z

Time-Body-Acc-std-X

Time-Body-Acc-std-Y

Time-Body-Acc-std-Z

Time-Gravity-Acc-mean-X

Time-Gravity-Acc-mean-Y

Time-Gravity-Acc-mean-Z

Time-Gravity-Acc-std-X

Time-Gravity-Acc-std-Y

Time-Gravity-Acc-std-Z

Time-Body-Acc-Jerk-mean-X

Time-Body-Acc-Jerk-mean-Y

Time-Body-Acc-Jerk-mean-Z

Time-Body-Acc-Jerk-std-X

Time-Body-Acc-Jerk-std-Y

Time-Body-Acc-Jerk-std-Z

Time-Body-Gyro-mean-X

Time-Body-Gyro-mean-Y

Time-Body-Gyro-mean-Z

Time-Body-Gyro-std-X

Time-Body-Gyro-std-Y

Time-Body-Gyro-std-Z

Time-Body-Gyro-Jerk-mean-X

Time-Body-Gyro-Jerk-mean-Y

Time-Body-Gyro-Jerk-mean-Z

Time-Body-Gyro-Jerk-std-X

Time-Body-Gyro-Jerk-std-Y

Time-Body-Gyro-Jerk-std-Z

Time-Body-Acc-Mag-mean

Time-Body-Acc-Mag-std

Time-Gravity-Acc-Mag-mean

Time-Gravity-Acc-Mag-std

Time-Body-Acc-Jerk-Mag-mean

Time-Body-Acc-Jerk-Mag-std

Time-Body-Gyro-Mag-mean

Time-Body-Gyro-Mag-std

Time-Body-Gyro-Jerk-Mag-mean

Time-Body-Gyro-Jerk-Mag-std

Freq-Body-Acc-mean-X

Freq-Body-Acc-mean-Y

Freq-Body-Acc-mean-Z

Freq-Body-Acc-std-X

Freq-Body-Acc-std-Y

Freq-Body-Acc-std-Z

Freq-Body-Acc-mean-Freq-X

Freq-Body-Acc-mean-Freq-Y

Freq-Body-Acc-mean-Freq-Z

Freq-Body-Acc-Jerk-mean-X

Freq-Body-Acc-Jerk-mean-Y

Freq-Body-Acc-Jerk-mean-Z

Freq-Body-Acc-Jerk-std-X

Freq-Body-Acc-Jerk-std-Y

Freq-Body-Acc-Jerk-std-Z

Freq-Body-Acc-Jerk-mean-Freq-X

Freq-Body-Acc-Jerk-mean-Freq-Y

Freq-Body-Acc-Jerk-mean-Freq-Z

Freq-Body-Gyro-mean-X

Freq-Body-Gyro-mean-Y

Freq-Body-Gyro-mean-Z

Freq-Body-Gyro-std-X

Freq-Body-Gyro-std-Y

Freq-Body-Gyro-std-Z

Freq-Body-Gyro-mean-Freq-X

Freq-Body-Gyro-mean-Freq-Y

Freq-Body-Gyro-mean-Freq-Z

Freq-Body-Acc-Mag-mean

Freq-Body-Acc-Mag-std

Freq-Body-Acc-Mag-mean-Freq

Freq-Body-Body-Acc-Jerk-Mag-mean

Freq-Body-Body-Acc-Jerk-Mag-std

Freq-Body-Body-Acc-Jerk-Mag-mean-Freq

Freq-Body-Body-Gyro-Mag-mean

Freq-Body-Body-Gyro-Mag-std

Freq-Body-Body-Gyro-Mag-mean-Freq

Freq-Body-Body-Gyro-Jerk-Mag-mean

Freq-Body-Body-Gyro-Jerk-Mag-std

Freq-Body-Body-Gyro-Jerk-Mag-mean-Freq
